source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.7.1'

gem 'core', path: ENV['DOCKER'] ? './vendor/gems/core' : '../core'
gem 'irb', '1.2.6'

group :test do
  gem 'rspec', '3.9.0'
  gem 'karafka-testing', '~> 1.3.0'
  gem 'simplecov', '~> 0.17.1', require: false
  gem 'sinatra', '~> 2.0.8'
  gem 'webmock', '~> 3.8.0'
end
