source "https://rubygems.org"

# Specify your gem's dependencies in ms_core.gemspec
gemspec

group :test do
  gem 'rspec', '3.9.0'
  gem 'factory_bot', '6.1.0'
  gem 'shoulda-matchers', '~> 4.3.0', require: false
  gem 'simplecov', '~> 0.17.1', require: false
  gem 'webmock', '~> 3.8.0'
end
